export const footerMainSiteLinks: string[] = [
    'FAQ',
    'Help Center',
    'Account',
    'Media Center',
    'Investor Relations',
    'Jobs',
    'Redeem Gift Cards',
    'Buy Gift Cards',
    'Ways to Watch',
    'Terms of Use',
    'Privacy',
    'Cookie Preferences',
    'Corporate Information',
    'Contact Us',
    'Speed Test',
    'Legal Guarantee',
    'Legal Notices',
    'Only on Netflix',
    'Ad Choices',
]

export const footerSignupSiteLinks: string[] = [
    'FAQ',
    'Help Center',
    'Netflix Shop',
    'Terms of Use',
    'Privacy',
    'Cookie Preferences',
    'Corporate Information',
    'Ad Choices',
]
